skillSummary = {
   "Acrobatics": {
      "Alchemist": "",
      "Barbarian": "C",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "C",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Dex"
   },
   "Appraise": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "C",
      "Sum": "",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Bluff": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "C",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "C",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Cha"
   },
   "Climb": {
      "Alchemist": "",
      "Barbarian": "C",
      "Bard": "C",
      "Cavalier": "C",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Str"
   },
   "Craft": {
      "Alchemist": "C",
      "Barbarian": "C",
      "Bard": "C",
      "Cavalier": "C",
      "Cleric": "C",
      "Druid": "C",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "C",
      "Oracle": "C",
      "Paladin": "C",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "C",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Diplomacy": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "C",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "",
      "Oracle": "C",
      "Paladin": "C",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Cha"
   },
   "Disable Device": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "No",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Dex"
   },
   "Disguise": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Cha"
   },
   "Escape Artist": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Dex"
   },
   "Fly": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "C",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "",
      "Sor": "C",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "Yes",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Dex"
   },
   "Handle Animal": {
      "Alchemist": "",
      "Barbarian": "C",
      "Bard": "",
      "Cavalier": "C",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "C",
      "Ranger": "C",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Cha"
   },
   "Heal": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "C",
      "Fighter": "",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "",
      "Oracle": "C",
      "Paladin": "C",
      "Ranger": "C",
      "Rog": "",
      "Sor": "",
      "Sum": "",
      "Wit": "C",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Wis"
   },
   "Intimidate": {
      "Alchemist": "",
      "Barbarian": "C",
      "Bard": "C",
      "Cavalier": "C",
      "Cleric": "",
      "Druid": "",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "C",
      "Sum": "",
      "Wit": "C",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Cha"
   },
   "Knowledge (arcana)": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "",
      "Sor": "C",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (dungeoneering)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "C",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (engineering)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (geography)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (history)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "C",
      "Oracle": "C",
      "Paladin": "",
      "Ranger": "",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (local)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "C",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (nature)": {
      "Alchemist": "C",
      "Barbarian": "C",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (nobility)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "C",
      "Ranger": "",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (planes)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "",
      "Oracle": "C",
      "Paladin": "",
      "Ranger": "",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Knowledge (religion)": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "C",
      "Oracle": "C",
      "Paladin": "C",
      "Ranger": "",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Linguistics": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Perception": {
      "Alchemist": "C",
      "Barbarian": "C",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Wis"
   },
   "Perform": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Cha"
   },
   "Profession": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "C",
      "Cleric": "C",
      "Druid": "C",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "C",
      "Oracle": "C",
      "Paladin": "C",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "C",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Wis"
   },
   "Ride": {
      "Alchemist": "",
      "Barbarian": "C",
      "Bard": "",
      "Cavalier": "C",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "C",
      "Ranger": "C",
      "Rog": "",
      "Sor": "",
      "Sum": "C",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Dex"
   },
   "Sense Motive": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "C",
      "Cleric": "C",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "C",
      "Oracle": "C",
      "Paladin": "C",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Wis"
   },
   "Sleight of Hand": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "C",
      "Inquisitor": "",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "No",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Dex"
   },
   "Spellcraft": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "C",
      "Druid": "C",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "",
      "Oracle": "C",
      "Paladin": "C",
      "Ranger": "C",
      "Rog": "",
      "Sor": "C",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "C",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Int"
   },
   "Stealth": {
      "Alchemist": "",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Dex"
   },
   "Survival": {
      "Alchemist": "C",
      "Barbarian": "C",
      "Bard": "",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "",
      "Key Ability": "Wis"
   },
   "Swim": {
      "Alchemist": "",
      "Barbarian": "C",
      "Bard": "",
      "Cavalier": "C",
      "Cleric": "",
      "Druid": "C",
      "Fighter": "C",
      "Gunslinger": "C",
      "Inquisitor": "C",
      "Magus": "C",
      "Monk": "C",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "C",
      "Rog": "C",
      "Sor": "",
      "Sum": "",
      "Wit": "",
      "Wiz": "",
      "Untrained": "Yes",
      "Armor Check Penalty": "Yes",
      "Key Ability": "Str"
   },
   "Use Magusic Device": {
      "Alchemist": "C",
      "Barbarian": "",
      "Bard": "C",
      "Cavalier": "",
      "Cleric": "",
      "Druid": "",
      "Fighter": "",
      "Gunslinger": "",
      "Inquisitor": "",
      "Magus": "C",
      "Monk": "",
      "Oracle": "",
      "Paladin": "",
      "Ranger": "",
      "Rog": "C",
      "Sor": "C",
      "Sum": "C",
      "Wit": "C",
      "Wiz": "",
      "Untrained": "No",
      "Armor Check Penalty": "",
      "Key Ability": "Cha"
   }
}
